version: '3'

services:
  api:
    container_name: project_prof_camp
    build:
      context: ./api
      dockerfile: Dockerfile-up
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
  jupyter:
    build:
      context: ./jupyter
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    ports:
      - "8888:8888"